<?php include $this->getOrigTemplate() ?>
<?php $_block = $this->getFoomanBlock() ?>
<?php if (Mage::helper('foomanjirafe')->isDashboardActive()) : ?>
    <link type="text/css" rel="stylesheet" href="<?php echo $_block->getAssetUrl('bundles/jirafedashboard/css/magento_ui.css') ?>" media="all" />
    <script type="text/javascript" src="<?php echo $_block->getAssetUrl('bundles/jirafedashboard/js/magento_ui.js') ?>"></script>
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl('js').'fooman/jirafe/noConflict.js'?>"></script>
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl('js').'fooman/jirafe/jirafe.js'?>"></script>    
<?php endif ?>
