<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @package     Fooman_Jirafe
 * @copyright   Copyright (c) 2010 Jirafe Inc (http://www.jirafe.com)
 * @copyright   Copyright (c) 2010 Fooman Limited (http://www.fooman.co.nz)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript" src="<?php echo $this->getAssetUrl('bundles/jirafedashboard/js/magento_ui.js') ?>"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js').'fooman/jirafe/noConflict.js'?>"></script>
<div id="jirafe"></div>
<script type="text/javascript">
<!--
if (typeof jQuery != 'undefined') { 
    (function($) {
         $('#jirafe').jirafe({
            api_url:    '<?php echo $this->getDashboardApiUrl()?>',
            api_token:  '<?php echo $this->getJirafeUserToken()?>',
            app_id:     '<?php echo $this->getJirafeApplicationId()?>'
         });
    })(jQuery);
}
-->
<!--
setTimeout(function() {
    if ($('mod-jirafe') == undefined){
        $('messages').insert ("<ul class=\"messages\"><li class=\"error-msg\">We're unable to connect with the Jirafe service for the moment. Please wait a few minutes and refresh this page later.</li></ul>");        
    }        
}, 2000);
-->
</script>
